TurstedBWeb/Areas/Admin/Controllers/BlobController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrustedB.DataAccess.Data;
using TrustedB.Models;
using TrustedB.Models.ViewModels;
using TrustedB.Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using TrustedBWeb.Logic;
using Container = TrustedB.Models.Container;

namespace TrustedB.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class BlobController : Controller
    {
        private readonly IBlobService _blobService;

        public BlobController(IBlobService blobService)
        {
            _blobService = blobService;
        }

        [HttpGet]
        public async Task<IActionResult> Manage(string containerName)
        {
            var blobsObj = await _blobService.GetAllBlobs(containerName);
            return View(blobsObj);
        }

        [HttpGet]
        public IActionResult AddFile(string containerName)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddFile(string containerName, Blob blob, IFormFile file)
        {
            if (file == null || file.Length < 1) return View();

            //file name - xps_img2.png 
            //new name - xps_img2_GUIDHERE.png
            var fileName =Guid.NewGuid() + Path.GetExtension(file.FileName);
            var result = await _blobService.UploadBlob(fileName, file, containerName, blob);

            if (result)
                return RedirectToAction("Index", "Container");

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ViewFile(string name, string containerName)
        {
           
            return Redirect(await _blobService.GetBlob(name, containerName));
        }

        public async Task<IActionResult> DeleteFile(string name, string containerName)
        {
            await _blobService.DeleteBlob(name, containerName);
            return RedirectToAction("Index", "Home");
        }

    }

}

TurstedBWeb/Areas/Admin/Controllers/ContainerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrustedB.DataAccess.Data;
using TrustedB.Models;
using TrustedB.Models.ViewModels;
using TrustedB.Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using TrustedBWeb.Logic;
using Container = TrustedB.Models.Container;

namespace TrustedB.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ContainerController : Controller
    {
        private readonly IContainerService _containerService;

        public ContainerController(IContainerService containerService)
        {
            _containerService = containerService;
        }

        public async Task<IActionResult> Index()
        {
            var allContainer = await _containerService.GetAllContainer();
            return View(allContainer);
        }

        public async Task<IActionResult> Delete(string containerName)
        {
            await _containerService.DeleteContainer(containerName);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create()
        {
            return View(new Container());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Container container)
        {
            await _containerService.CreateContainer(container.Name);
            return RedirectToAction(nameof(Index));
        }
    }

}

TurstedBWeb/Areas/Admin/Views/Container/Create.cshtml
@model Container

    <div class="container border p-3">
        <h2 class="text-info pb-2">Create Container</h2>
        <form method="post" asp-action="Create">
            <div class="backgroundWhite">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Name" class="col-form-label"></label>
                    </div>
                    <div class="col-5">
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input type="submit" class="btn btn-info form-control" value="Create" />
                    </div>
                    <div class="col-6">
                        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    @section Scripts{
        @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

TurstedBWeb/Areas/Admin/Views/Container/Index.cshtml
@model List<string>

<br />
<br />
<div class="border backgroundWhite p-4">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info"> Container List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp;  Create New </a>
        </div>
    </div>
    <br />
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        Container Name
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item)
                        </td>
                        <td>
                            <a class="btn btn-primary text-white" asp-action="Manage" asp-controller="Blob" asp-route-containerName="@item">
                             Manage
                            </a>

                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-containerName="@item">
                               Delete
                            </a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No category exists...</p>
        }
    </div>
</div>