TurstedBWeb/Areas/Admin/Controllers/ContainerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrustedB.DataAccess.Data;
using TrustedB.Models;
using TrustedB.Models.ViewModels;
using TrustedB.Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using TrustedBWeb.Logic;
using Container = TrustedB.Models.Container;

namespace TrustedB.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class ContainerController : Controller
    {
        private readonly IContainerService _containerService;

        public ContainerController(IContainerService containerService)
        {
            _containerService = containerService;
        }

        public async Task<IActionResult> Index()
        {
            var allContainer = await _containerService.GetAllContainer();
            return View(allContainer);
        }

        public async Task<IActionResult> Delete(string containerName)
        {
            await _containerService.DeleteContainer(containerName);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create()
        {
            return View(new Container());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Container container)
        {
            await _containerService.CreateContainer(container.Name);
            return RedirectToAction(nameof(Index));
        }
    }

}

TurstedBWeb/Areas/Admin/Controllers/TopicController.cs
using Azure.Core;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;
using System.Diagnostics;
using System.Reflection.Metadata;
using System.Security.Claims;
using System.Text.RegularExpressions;
using TrustedB.DataAccess.Repository;
using TrustedB.Models;
using TrustedB.Models.ViewModels;
using TrustedB.Utility;
using TrustedBWeb.Logic;
using TurstedB.DataAccess.Repository.IRepository;
using TurstedBWeb.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Reflection.Metadata.BlobBuilder;

namespace TrustedBWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ILogger<TopicController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IBlobService _blobService;
        private readonly IConfiguration _configuration;
        private readonly BlobServiceClient _blobClient;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IWebHostEnvironment _hostEnvironment;
        public string fileName = "";
        public string slash = @"\";

        //private readonly IBlobService _blobService;
        //public var topicList;
        public TopicController(ILogger<TopicController> logger, IWebHostEnvironment hostEnvironment, IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, IBlobService blobService, BlobServiceClient blobClient, IConfiguration configuration)
        {
            _logger = logger;
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _blobService = blobService;
            _blobClient = blobClient;
            _configuration = configuration;
        }

        public IActionResult Index(int pg = 1)
        {
            var topicList = new List<Topics>();
            const int pageSize = 10;
            if (pg < 1) { pg = 1; }

            int recsCount = _unitOfWork.Topics.GetAll().Count();
            var pager = new Pager(null, recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
           
            topicList = _unitOfWork.Topics.GetAllPagination(recSkip, pager.PageSize,null, includeProperties: "ApplicationUser,TopicsStates,Category").ToList();

            this.ViewBag.Pager = pager;

            //  topicList = _unitOfWork.Topics.GetAll(includeProperties: "ApplicationUser,TopicsStates,Category").ToList();


            return View(topicList);
        }



        public IActionResult Upsert(Guid? id)
        {
            TopicVM topicVM = new()
            {
                topic = new Topics(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.ArabicName,
                    Value = i.CategoryId.ToString()
                }),
                SubCategoryList = _unitOfWork.SubCategory.GetAll().Select(i => new SelectListItem
                {
                    Text = i.SubArabicName,
                    Value = i.SubCategoryId.ToString()
                })
            };

            if (id == null)
            {
                //new 
                return View(topicVM);
            }
            else
            {
                //eidt
                topicVM.topic = _unitOfWork.Topics.Get(u => u.TopicId == id, includeProperties: "ApplicationUser,TopicsStates,Category");
                topicVM.StateHistoryList = _unitOfWork.StateHistory.GetAll(filter: o => (o.TopicId == topicVM.topic.TopicId), includeProperties: "ApplicationUser").ToList();
                topicVM.AttachmentsList = _unitOfWork.Attachments.GetAll(filter: o => (o.TopicId == topicVM.topic.TopicId), includeProperties: "ApplicationUser,TopicsStates").ToList();
                topicVM.CommentList = _unitOfWork.CommentHistory.GetAll(filter: o => (o.TopicId == topicVM.topic.TopicId), includeProperties: "ApplicationUser,TopicsStates").ToList();

                return View(topicVM);
            }

        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> UpsertAsync(TopicVM topicVM)
        {
            var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            var culture = rqf.RequestCulture.Culture;

            var userLoginId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicationuser = _unitOfWork.ApplicationUser.Get(u => u.Id == userLoginId);
            topicVM.applicationUser = applicationuser;
            List<string> exsitingUserRoles = await _userManager.GetRolesAsync(applicationuser) as List<string>;


            Handel handel = new Handel(_unitOfWork);
            if (ModelState.IsValid)
            {

               // var userLoginId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                //add new topic
                if (topicVM.topic.TopicId == Guid.Empty)
                {

                    topicVM.topic.CreationDate = DateTime.UtcNow.AddMinutes(180).ToString();
                    topicVM.topic.ApplicationUserId = userLoginId;
                    topicVM.topic.stateId = 1;
                    _unitOfWork.Topics.Add(topicVM.topic);

                    var Shistory = new StateHistory();
                    Shistory.State = handel.StateName(1);
                    Shistory.TopicId = topicVM.topic.TopicId;
                    Shistory.ApplicationUserId = userLoginId;
                    Shistory.StateSetDate = DateTime.UtcNow.AddMinutes(180).ToString();
                    _unitOfWork.StateHistory.Add(Shistory);


                }
                else //Eidt new topic

                {
                    //var newState = topicVM.topic.stateId;
                    var oldTopic = _unitOfWork.Topics.Get(u => u.TopicId == topicVM.topic.TopicId);
                   
                    
                    bool transition = handel.StateTransition(oldTopic.stateId, topicVM.topic.stateId, exsitingUserRoles);
                    if (!transition)
                    {
                        TempData[SD.Error] = culture.Name == "ar" ? "عفوا ليس لديك الصلاحية المناسبة" : "Sorry you havn't permission";
                        return RedirectToAction("Upsert", new { id = topicVM.topic.TopicId });
                    }


                    if (oldTopic.stateId != topicVM.topic.stateId && transition)
                    {
                        //topicVM.topic = oldTopic;
                        oldTopic.stateId = topicVM.topic.stateId;
                        //var test = oldTopic;
                        _unitOfWork.Topics.Update(oldTopic);

                        var Shistory = new StateHistory();
                        Shistory.State = handel.StateName(topicVM.topic.stateId);
                        Shistory.TopicId = topicVM.topic.TopicId;
                        Shistory.ApplicationUserId = userLoginId;
                        Shistory.StateSetDate = DateTime.UtcNow.AddMinutes(180).ToString();
                        _unitOfWork.StateHistory.Add(Shistory);
                    }
                    else
                    {
                        if (topicVM.topic.Titel != null)
                            topicVM.topic.stateId = oldTopic.stateId;
                        topicVM.topic.CreationDate = oldTopic.CreationDate;
                        topicVM.topic.ApplicationUserId = oldTopic.ApplicationUserId;
                        topicVM.topic.MainFile = oldTopic.MainFile; 
                            _unitOfWork.Topics.Update(topicVM.topic);
                    }
                }

                _unitOfWork.Save();
                return RedirectToAction("Upsert", new { id = topicVM.topic.TopicId });

            }
            else
            {
                return View(topicVM);
            }

        }

        //__________________download______________________

        public async Task<IActionResult> DownloadFileAsync(Guid? id)
        {
            
            var fileName = _unitOfWork.Attachments.Get(u => u.FileId == id);
            
            List<string> storageData = new List<string>();
            foreach (var includeProp in fileName.FilePath
                    .Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries))
            {
                storageData.Add(includeProp);
            }

            var blobName = storageData[3];
            var containerName = storageData[2];

            CloudBlockBlob blockBlob;
            await using (MemoryStream memoryStream = new MemoryStream())
            {
                string blobstorageconnection = _configuration.GetValue<string>("BlobConnection");
                CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);
                CloudBlobClient cloudBlobClient = cloudStorageAccount.CreateCloudBlobClient();
                CloudBlobContainer cloudBlobContainer = cloudBlobClient.GetContainerReference(containerName);
                blockBlob = cloudBlobContainer.GetBlockBlobReference(blobName);
                await blockBlob.DownloadToStreamAsync(memoryStream);
            }
            Stream blobStream = blockBlob.OpenReadAsync().Result;
            return File(blobStream, blockBlob.Properties.ContentType, blockBlob.Name);

        }


        //______________________________Attachments_________________

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> Attachment(Guid? id, TopicVM topicVM)
        {
            //Handel handel = new Handel(_unitOfWork);

TurstedBWeb/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrustedB.DataAccess.Data;
using TrustedB.Models;
using TrustedB.Models.ViewModels;
using TrustedB.Utility;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace TrustedB.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(ApplicationDbContext db, UserManager<ApplicationUser> userManager,
           RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userList = _db.ApplicationUser.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var user_role = await _userManager.GetRolesAsync(user) as List<string>;
                user.Role = String.Join(",", user_role);

            }
            return View(userList);
        }

        public async Task<IActionResult> ManageRole(string userId)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            List<string> exsitingUserRoles = await _userManager.GetRolesAsync(user) as List<string>;
            var model = new RolesViewModel()
            {
                User = user
            };

            foreach (var role in _roleManager.Roles)
            {
                RoleSelection roleSelection = new()
                {
                    RoleName = role.Name
                };
                if (exsitingUserRoles.Any(c => c == role.Name))
                {
                    roleSelection.IsSelected = true;
                }
                model.RolesList.Add(roleSelection);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRole(RolesViewModel rolesViewModel)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(rolesViewModel.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var oldUserRoles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, oldUserRoles);

            if (!result.Succeeded)
            {
                TempData[SD.Error] = "Error while removing roles";
                return View(rolesViewModel);
            }

            result = await _userManager.AddToRolesAsync(user,
                rolesViewModel.RolesList.Where(x => x.IsSelected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                TempData[SD.Error] = "Error while adding roles";
                return View(rolesViewModel);
            }

            TempData[SD.Success] = "Roles assigned successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockUnlock(string userId)
        {
            ApplicationUser user = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId);
            if (user == null)
            {
                return NotFound();
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                //user is locked and will remain locked untill lockoutend time
                //clicking on this action will unlock them
                user.LockoutEnd = DateTime.Now;
                TempData[SD.Success] = "User unlocked successfully";
            }
            else
            {
                //user is not locked, and we want to lock the user
                user.LockoutEnd = DateTime.Now.AddYears(1000);
                TempData[SD.Success] = "User locked successfully";
            }
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


    }
}

TurstedBWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] BWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/toastr.css" asp-append-version="true" />

 @*    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" /> *@


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

</head>
<body>
    <header>
        @* <div class="container-fluid"> *@

        <div class="col-12 bg-primary d-inline-flex justify-content-between">
                <div class="px-2">

                    <ul class="navbar-nav pull-left">



                        <li class="nav-item d-inline-flex">
                            <a class="nav-link text-white"> <i class="bi bi-envelope h6 m-1"></i>@_localization.Getkey("Test@test.com")</a> 
                       @*  <a class="nav-link text-white h6"> Testing Testing</a> *@
                        </li>

                    </ul>

                </div>
         
            
            <div class=" px-5">
                <ul class="navbar mt-1">
                    <li class="nav-item dropdown position-absolute top-20 start-0 mt-3">
                        <a class="nav-link dropdown-toggle text-white " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-translate h4"></i>
                        </a>
                        <ul class="dropdown-menu position-absolute top-5 start-0">
                            <li class="nav-item">
                                <a class="dropdown-item text-center " asp-action="ChangeLanguage" asp-area="Customer" asp-controller="Home" asp-route-culture="ar"> @_localization.Getkey("عربي")</a>
                            </li>

                            <li class="nav-item">
                                <a class="dropdown-item text-center" asp-action="ChangeLanguage" asp-area="Customer" asp-controller="Home" asp-route-culture="en"> @_localization.Getkey("English") </a>
                            </li>
                        </ul>
                    </li>


                </ul>
            </div>
          @*   </div> *@
            @* <div id="top-header">
                <nav class="navbar navbar-expand-lg" style="height: 2rem;">
                   

                        <div class="col-lg-6 col-md-6 col-sm-6 p-2">
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                                <ul class="navbar-nav pull-left">



                                    <li class="nav-item">
                                        <a class="nav-link text-white"> <i class="bi bi-envelope h6 m-1"></i>@_localization.Getkey("Test@test.com")</a>
                                    </li>

                                </ul>

                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 p-2 ">
                            <ul class="navbar">
                                <li class="nav-item dropdown position-absolute top-20 start-0 mt-3">
                                    <a class="nav-link dropdown-toggle text-white " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-translate h4"></i>
                                    </a>
                                    <ul class="dropdown-menu position-absolute top-5 start-0">
                                        <li class="nav-item">
                                            <a class="dropdown-item text-center " asp-action="ChangeLanguage" asp-area="Customer" asp-controller="Home" asp-route-culture="ar"> @_localization.Getkey("عربي")</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="dropdown-item text-center" asp-action="ChangeLanguage" asp-area="Customer" asp-controller="Home" asp-route-culture="en"> @_localization.Getkey("English") </a>
                                        </li>
                                    </ul>
                                </li>


                            </ul>
                        </div>
                      

                  
            
            </nav>
            </div> *@

        </div>
      

      @*   <div class="row"> *@
            <nav class="navbar navbar-expand-lg border-bottom border-primary border-3 shadow px-5">
           
            <div class="container-fluid ">


                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                       <img src="~/Files/Logo/BName.png" class="" style="width:140px;" /> 

                    </a>

                    <ul class="navbar-nav ">
                        <li class="nav-item ">
                            <a class="nav-link active fs-6" asp-area="Customer" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house-door h5"></i>
                                @_localization.Getkey("Home")
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-route-SubCategoryID="1" asp-action="Guidance">@_localization.Getkey("News")</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-route-SubCategoryID="2" asp-action="AllImages">@_localization.Getkey("Images")</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-route-SubCategoryID="6" asp-action="AllAudio">@_localization.Getkey("Audios")</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-route-SubCategoryID ="4" asp-action="AllVideos">@_localization.Getkey("Vedios")</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-route-SubCategoryID="8" asp-action="AllPDF">@_localization.Getkey("Reading")</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Container" asp-action="Index">Container</a>
                        </li> *@
                        

                    </ul>


                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">

                        <img src="~/Files/Logo/Blogo.png" class="" style="width:50px;" /> 

                    </a>


                </div>
            </div>

        </nav> 
       @*  </div> *@
    </header>
    <div>
        <main class="main" role="main">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>
   
    <footer class="bg-primary text-light text-center " style="bottom:0;position: fixed; width:100%;">
            <div class="row">
                <div class="col-6 d-sm-inline-flex justify-content-between px-5">
                    
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="Topic" asp-action="Index">@_localization.Getkey("Topics")</a>
                       

                        
                            <a class="nav-link text-white" asp-area="Admin" asp-controller="User" asp-action="Index">@_localization.Getkey("Users")</a>
                     
                </div>
                
                <div class="col-6">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </footer>
 

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toastr.js" asp-append-version="true"></script>




    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>

TurstedBWeb/Views/Shared/_Notifications.cshtml
@if (TempData[SD.Success] != null)
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.success('@TempData[SD.Success]');
    </script>
}

@if (TempData[SD.Error] != null)
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.error('@TempData[SD.Error]');
    </script>
}